GET /api/channels
Accept: application/json
Cache-Control: no-cache
Host: tv.isokol-dev.ru

###

GET /api/channels?maxResults=10
Accept: application/json
Cache-Control: no-cache
Host: tv.isokol-dev.ru

###

GET /api/channels?pageToken=IEHCMVIPKy6lVRUIs8INHpZUWMgwT8x4q3psH5PtMHo=
Accept: application/json
Cache-Control: no-cache
Host: tv.isokol-dev.ru

###

GET /api/categories
Accept: application/json
Cache-Control: no-cache
Host: tv.isokol-dev.ru

###

GET /api/categories?maxResults=10
Accept: application/json
Cache-Control: no-cache
Host: tv.isokol-dev.ru

###

GET /api/categories?pageToen=
Accept: application/json
Cache-Control: no-cache
Host: tv.isokol-dev.ru

###

GET /api/programme
Accept: application/json
Cache-Control: no-cache
Host: tv.isokol-dev.ru

###

GET /api/programme?maxResults=5
Accept: application/json
Cache-Control: no-cache
Host: tv.isokol-dev.ru

###

GET /api/programme?pageToken=BZ7fgMg6TSHHxXu9snjk9m4NPba3CaUY14ju1s/KUaU=
Accept: application/json
Cache-Control: no-cache
Host: tv.isokol-dev.ru

###