GET /api/channels
Accept: application/json
Cache-Control: no-cache
Host: tv.isokol-dev.ru

###

GET /api/categories
Accept: application/json
Cache-Control: no-cache
Host: tv.isokol-dev.ru

###


GET /api/channels?id=2
Accept: application/json
Cache-Control: no-cache
Host: tv.isokol-dev.ru

###

GET /api/programme?channel-id=2
Accept: application/json
Cache-Control: no-cache
Host: tv.isokol-dev.ru

###

GET /api/programme
Accept: application/json
Cache-Control: no-cache
Host: tv.isokol-dev.ru

###